//
// Copyright © 2024 honeysense.com All rights reserved.
// Author: sunrui
// Date: 2024-03-26 10:33:51

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.33.0
// 	protoc        v4.25.3
// source: pkg/rpc/chat/message/message_audio.proto

package message

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 音频
type MessageAudio struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Uri:
	//
	//	*MessageAudio_AliasName
	//	*MessageAudio_Hash
	//	*MessageAudio_Url
	Uri isMessageAudio_Uri `protobuf_oneof:"Uri"`
}

func (x *MessageAudio) Reset() {
	*x = MessageAudio{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_rpc_chat_message_message_audio_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MessageAudio) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageAudio) ProtoMessage() {}

func (x *MessageAudio) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_rpc_chat_message_message_audio_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageAudio.ProtoReflect.Descriptor instead.
func (*MessageAudio) Descriptor() ([]byte, []int) {
	return file_pkg_rpc_chat_message_message_audio_proto_rawDescGZIP(), []int{0}
}

func (m *MessageAudio) GetUri() isMessageAudio_Uri {
	if m != nil {
		return m.Uri
	}
	return nil
}

func (x *MessageAudio) GetAliasName() string {
	if x, ok := x.GetUri().(*MessageAudio_AliasName); ok {
		return x.AliasName
	}
	return ""
}

func (x *MessageAudio) GetHash() string {
	if x, ok := x.GetUri().(*MessageAudio_Hash); ok {
		return x.Hash
	}
	return ""
}

func (x *MessageAudio) GetUrl() string {
	if x, ok := x.GetUri().(*MessageAudio_Url); ok {
		return x.Url
	}
	return ""
}

type isMessageAudio_Uri interface {
	isMessageAudio_Uri()
}

type MessageAudio_AliasName struct {
	AliasName string `protobuf:"bytes,1,opt,name=aliasName,proto3,oneof"`
}

type MessageAudio_Hash struct {
	Hash string `protobuf:"bytes,2,opt,name=hash,proto3,oneof"`
}

type MessageAudio_Url struct {
	Url string `protobuf:"bytes,3,opt,name=url,proto3,oneof"`
}

func (*MessageAudio_AliasName) isMessageAudio_Uri() {}

func (*MessageAudio_Hash) isMessageAudio_Uri() {}

func (*MessageAudio_Url) isMessageAudio_Uri() {}

var File_pkg_rpc_chat_message_message_audio_proto protoreflect.FileDescriptor

var file_pkg_rpc_chat_message_message_audio_proto_rawDesc = []byte{
	0x0a, 0x28, 0x70, 0x6b, 0x67, 0x2f, 0x72, 0x70, 0x63, 0x2f, 0x63, 0x68, 0x61, 0x74, 0x2f, 0x6d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x5f, 0x61,
	0x75, 0x64, 0x69, 0x6f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x14, 0x70, 0x6b, 0x67, 0x2e,
	0x72, 0x70, 0x63, 0x2e, 0x63, 0x68, 0x61, 0x74, 0x2e, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x22, 0x5f, 0x0a, 0x0c, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x41, 0x75, 0x64, 0x69, 0x6f,
	0x12, 0x1e, 0x0a, 0x09, 0x61, 0x6c, 0x69, 0x61, 0x73, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x09, 0x61, 0x6c, 0x69, 0x61, 0x73, 0x4e, 0x61, 0x6d, 0x65,
	0x12, 0x14, 0x0a, 0x04, 0x68, 0x61, 0x73, 0x68, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00,
	0x52, 0x04, 0x68, 0x61, 0x73, 0x68, 0x12, 0x12, 0x0a, 0x03, 0x75, 0x72, 0x6c, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x03, 0x75, 0x72, 0x6c, 0x42, 0x05, 0x0a, 0x03, 0x55, 0x72,
	0x69, 0x42, 0x16, 0x5a, 0x14, 0x70, 0x6b, 0x67, 0x2f, 0x72, 0x70, 0x63, 0x2f, 0x63, 0x68, 0x61,
	0x74, 0x2f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_pkg_rpc_chat_message_message_audio_proto_rawDescOnce sync.Once
	file_pkg_rpc_chat_message_message_audio_proto_rawDescData = file_pkg_rpc_chat_message_message_audio_proto_rawDesc
)

func file_pkg_rpc_chat_message_message_audio_proto_rawDescGZIP() []byte {
	file_pkg_rpc_chat_message_message_audio_proto_rawDescOnce.Do(func() {
		file_pkg_rpc_chat_message_message_audio_proto_rawDescData = protoimpl.X.CompressGZIP(file_pkg_rpc_chat_message_message_audio_proto_rawDescData)
	})
	return file_pkg_rpc_chat_message_message_audio_proto_rawDescData
}

var file_pkg_rpc_chat_message_message_audio_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_pkg_rpc_chat_message_message_audio_proto_goTypes = []interface{}{
	(*MessageAudio)(nil), // 0: pkg.rpc.chat.message.MessageAudio
}
var file_pkg_rpc_chat_message_message_audio_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_pkg_rpc_chat_message_message_audio_proto_init() }
func file_pkg_rpc_chat_message_message_audio_proto_init() {
	if File_pkg_rpc_chat_message_message_audio_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_pkg_rpc_chat_message_message_audio_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MessageAudio); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_pkg_rpc_chat_message_message_audio_proto_msgTypes[0].OneofWrappers = []interface{}{
		(*MessageAudio_AliasName)(nil),
		(*MessageAudio_Hash)(nil),
		(*MessageAudio_Url)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pkg_rpc_chat_message_message_audio_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pkg_rpc_chat_message_message_audio_proto_goTypes,
		DependencyIndexes: file_pkg_rpc_chat_message_message_audio_proto_depIdxs,
		MessageInfos:      file_pkg_rpc_chat_message_message_audio_proto_msgTypes,
	}.Build()
	File_pkg_rpc_chat_message_message_audio_proto = out.File
	file_pkg_rpc_chat_message_message_audio_proto_rawDesc = nil
	file_pkg_rpc_chat_message_message_audio_proto_goTypes = nil
	file_pkg_rpc_chat_message_message_audio_proto_depIdxs = nil
}
