//
// Copyright © 2024 honeysense.com All rights reserved.
// Author: sunrui
// Date: 2024-03-26 14:03:40

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v4.25.3
// source: internal/rpc/message/room_chat/room_chat.proto

package room_chat

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	RoomChat_Receive_FullMethodName = "/internal.rpc.message.room_chat.RoomChat/Receive"
)

// RoomChatClient is the client API for RoomChat service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RoomChatClient interface {
	// 接收
	Receive(ctx context.Context, in *ReceiveRequest, opts ...grpc.CallOption) (RoomChat_ReceiveClient, error)
}

type roomChatClient struct {
	cc grpc.ClientConnInterface
}

func NewRoomChatClient(cc grpc.ClientConnInterface) RoomChatClient {
	return &roomChatClient{cc}
}

func (c *roomChatClient) Receive(ctx context.Context, in *ReceiveRequest, opts ...grpc.CallOption) (RoomChat_ReceiveClient, error) {
	stream, err := c.cc.NewStream(ctx, &RoomChat_ServiceDesc.Streams[0], RoomChat_Receive_FullMethodName, opts...)
	if err != nil {
		return nil, err
	}
	x := &roomChatReceiveClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type RoomChat_ReceiveClient interface {
	Recv() (*ReceiveReply, error)
	grpc.ClientStream
}

type roomChatReceiveClient struct {
	grpc.ClientStream
}

func (x *roomChatReceiveClient) Recv() (*ReceiveReply, error) {
	m := new(ReceiveReply)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// RoomChatServer is the server API for RoomChat service.
// All implementations must embed UnimplementedRoomChatServer
// for forward compatibility
type RoomChatServer interface {
	// 接收
	Receive(*ReceiveRequest, RoomChat_ReceiveServer) error
	mustEmbedUnimplementedRoomChatServer()
}

// UnimplementedRoomChatServer must be embedded to have forward compatible implementations.
type UnimplementedRoomChatServer struct {
}

func (UnimplementedRoomChatServer) Receive(*ReceiveRequest, RoomChat_ReceiveServer) error {
	return status.Errorf(codes.Unimplemented, "method Receive not implemented")
}
func (UnimplementedRoomChatServer) mustEmbedUnimplementedRoomChatServer() {}

// UnsafeRoomChatServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RoomChatServer will
// result in compilation errors.
type UnsafeRoomChatServer interface {
	mustEmbedUnimplementedRoomChatServer()
}

func RegisterRoomChatServer(s grpc.ServiceRegistrar, srv RoomChatServer) {
	s.RegisterService(&RoomChat_ServiceDesc, srv)
}

func _RoomChat_Receive_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ReceiveRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(RoomChatServer).Receive(m, &roomChatReceiveServer{stream})
}

type RoomChat_ReceiveServer interface {
	Send(*ReceiveReply) error
	grpc.ServerStream
}

type roomChatReceiveServer struct {
	grpc.ServerStream
}

func (x *roomChatReceiveServer) Send(m *ReceiveReply) error {
	return x.ServerStream.SendMsg(m)
}

// RoomChat_ServiceDesc is the grpc.ServiceDesc for RoomChat service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RoomChat_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "internal.rpc.message.room_chat.RoomChat",
	HandlerType: (*RoomChatServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Receive",
			Handler:       _RoomChat_Receive_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "internal/rpc/message/room_chat/room_chat.proto",
}
