//
// Copyright © 2024 honeysense.com All rights reserved.
// Author: sunrui
// Date: 2024-03-26 10:24:25

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.33.0
// 	protoc        v4.25.3
// source: pkg/rpc/proto/chat/chat_quoted.proto

package chat

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 引用
type ChatQuoted struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SequenceId int32 `protobuf:"varint,1,opt,name=sequenceId,proto3" json:"sequenceId,omitempty"` // 引用消息序号
	// Types that are assignable to Type:
	//
	//	*ChatQuoted_Text
	Type isChatQuoted_Type `protobuf_oneof:"Type"`
}

func (x *ChatQuoted) Reset() {
	*x = ChatQuoted{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_rpc_proto_chat_chat_quoted_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ChatQuoted) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatQuoted) ProtoMessage() {}

func (x *ChatQuoted) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_rpc_proto_chat_chat_quoted_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatQuoted.ProtoReflect.Descriptor instead.
func (*ChatQuoted) Descriptor() ([]byte, []int) {
	return file_pkg_rpc_proto_chat_chat_quoted_proto_rawDescGZIP(), []int{0}
}

func (x *ChatQuoted) GetSequenceId() int32 {
	if x != nil {
		return x.SequenceId
	}
	return 0
}

func (m *ChatQuoted) GetType() isChatQuoted_Type {
	if m != nil {
		return m.Type
	}
	return nil
}

func (x *ChatQuoted) GetText() *ChatText {
	if x, ok := x.GetType().(*ChatQuoted_Text); ok {
		return x.Text
	}
	return nil
}

type isChatQuoted_Type interface {
	isChatQuoted_Type()
}

type ChatQuoted_Text struct {
	Text *ChatText `protobuf:"bytes,2,opt,name=text,proto3,oneof"` // 文本
}

func (*ChatQuoted_Text) isChatQuoted_Type() {}

var File_pkg_rpc_proto_chat_chat_quoted_proto protoreflect.FileDescriptor

var file_pkg_rpc_proto_chat_chat_quoted_proto_rawDesc = []byte{
	0x0a, 0x24, 0x70, 0x6b, 0x67, 0x2f, 0x72, 0x70, 0x63, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f,
	0x63, 0x68, 0x61, 0x74, 0x2f, 0x63, 0x68, 0x61, 0x74, 0x5f, 0x71, 0x75, 0x6f, 0x74, 0x65, 0x64,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x12, 0x70, 0x6b, 0x67, 0x2e, 0x72, 0x70, 0x63, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x63, 0x68, 0x61, 0x74, 0x1a, 0x22, 0x70, 0x6b, 0x67, 0x2f,
	0x72, 0x70, 0x63, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x63, 0x68, 0x61, 0x74, 0x2f, 0x63,
	0x68, 0x61, 0x74, 0x5f, 0x74, 0x65, 0x78, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x68,
	0x0a, 0x0a, 0x43, 0x68, 0x61, 0x74, 0x51, 0x75, 0x6f, 0x74, 0x65, 0x64, 0x12, 0x1e, 0x0a, 0x0a,
	0x73, 0x65, 0x71, 0x75, 0x65, 0x6e, 0x63, 0x65, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x0a, 0x73, 0x65, 0x71, 0x75, 0x65, 0x6e, 0x63, 0x65, 0x49, 0x64, 0x12, 0x32, 0x0a, 0x04,
	0x74, 0x65, 0x78, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x70, 0x6b, 0x67,
	0x2e, 0x72, 0x70, 0x63, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x63, 0x68, 0x61, 0x74, 0x2e,
	0x43, 0x68, 0x61, 0x74, 0x54, 0x65, 0x78, 0x74, 0x48, 0x00, 0x52, 0x04, 0x74, 0x65, 0x78, 0x74,
	0x42, 0x06, 0x0a, 0x04, 0x54, 0x79, 0x70, 0x65, 0x42, 0x14, 0x5a, 0x12, 0x70, 0x6b, 0x67, 0x2f,
	0x72, 0x70, 0x63, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x63, 0x68, 0x61, 0x74, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_pkg_rpc_proto_chat_chat_quoted_proto_rawDescOnce sync.Once
	file_pkg_rpc_proto_chat_chat_quoted_proto_rawDescData = file_pkg_rpc_proto_chat_chat_quoted_proto_rawDesc
)

func file_pkg_rpc_proto_chat_chat_quoted_proto_rawDescGZIP() []byte {
	file_pkg_rpc_proto_chat_chat_quoted_proto_rawDescOnce.Do(func() {
		file_pkg_rpc_proto_chat_chat_quoted_proto_rawDescData = protoimpl.X.CompressGZIP(file_pkg_rpc_proto_chat_chat_quoted_proto_rawDescData)
	})
	return file_pkg_rpc_proto_chat_chat_quoted_proto_rawDescData
}

var file_pkg_rpc_proto_chat_chat_quoted_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_pkg_rpc_proto_chat_chat_quoted_proto_goTypes = []interface{}{
	(*ChatQuoted)(nil), // 0: pkg.rpc.proto.chat.ChatQuoted
	(*ChatText)(nil),   // 1: pkg.rpc.proto.chat.ChatText
}
var file_pkg_rpc_proto_chat_chat_quoted_proto_depIdxs = []int32{
	1, // 0: pkg.rpc.proto.chat.ChatQuoted.text:type_name -> pkg.rpc.proto.chat.ChatText
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_pkg_rpc_proto_chat_chat_quoted_proto_init() }
func file_pkg_rpc_proto_chat_chat_quoted_proto_init() {
	if File_pkg_rpc_proto_chat_chat_quoted_proto != nil {
		return
	}
	file_pkg_rpc_proto_chat_chat_text_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_pkg_rpc_proto_chat_chat_quoted_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ChatQuoted); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_pkg_rpc_proto_chat_chat_quoted_proto_msgTypes[0].OneofWrappers = []interface{}{
		(*ChatQuoted_Text)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pkg_rpc_proto_chat_chat_quoted_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pkg_rpc_proto_chat_chat_quoted_proto_goTypes,
		DependencyIndexes: file_pkg_rpc_proto_chat_chat_quoted_proto_depIdxs,
		MessageInfos:      file_pkg_rpc_proto_chat_chat_quoted_proto_msgTypes,
	}.Build()
	File_pkg_rpc_proto_chat_chat_quoted_proto = out.File
	file_pkg_rpc_proto_chat_chat_quoted_proto_rawDesc = nil
	file_pkg_rpc_proto_chat_chat_quoted_proto_goTypes = nil
	file_pkg_rpc_proto_chat_chat_quoted_proto_depIdxs = nil
}
